<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Append-only evidence, administrative audit trail, certificates and notifications.
 *
 * `compliance_events` is written once and never updated. Four decisions exist here from the
 * first migration so the future offline iPad app needs no schema rewrite: a client-generated
 * UUID, the `occurred_at` / `received_at` split, `device_id` + `session_id`, and an
 * ingestion path that is idempotent on the UUID. See docs/product-spec.md §11 and §13.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('compliance_events', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->cascadeOnDelete();
            // Generated by the client so a replayed sync batch inserts nothing twice.
            $table->uuid('uuid')->unique();
            $table->string('event_type')->index();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignId('assignment_id')->nullable()
                ->constrained('user_training_assignments')->nullOnDelete();
            $table->foreignId('course_version_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('lesson_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('course_attempt_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('lesson_attempt_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('question_id')->nullable()->constrained()->nullOnDelete();
            $table->string('device_id')->nullable()->index();
            $table->string('session_id')->nullable();
            // What the device claims happened, and when the server actually received it.
            $table->timestamp('occurred_at')->index();
            $table->timestamp('received_at');
            $table->unsignedBigInteger('client_sequence')->nullable();
            $table->unsignedInteger('position_seconds')->nullable();
            $table->json('metadata')->nullable();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->timestamp('created_at')->nullable();

            $table->index(['assignment_id', 'occurred_at']);
            $table->index(['user_id', 'occurred_at']);
        });

        Schema::create('audit_logs', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->cascadeOnDelete();
            $table->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();
            $table->string('action')->index();
            $table->string('auditable_type')->nullable();
            $table->unsignedBigInteger('auditable_id')->nullable();
            $table->json('before')->nullable();
            $table->json('after')->nullable();
            $table->json('metadata')->nullable();
            $table->string('ip_address', 45)->nullable();
            $table->timestamp('created_at')->nullable();

            $table->index(['auditable_type', 'auditable_id']);
        });

        Schema::create('certificates', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->cascadeOnDelete();
            $table->string('certificate_number')->unique();
            // Public lookup key for the verification page — never the internal id.
            $table->string('verification_code')->unique();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignId('assignment_id')->constrained('user_training_assignments')->cascadeOnDelete();
            $table->foreignId('course_id')->constrained()->restrictOnDelete();
            $table->foreignId('course_version_id')->constrained()->restrictOnDelete();
            $table->timestamp('issued_at');
            $table->timestamp('expires_at')->nullable();
            $table->unsignedTinyInteger('score')->nullable();
            $table->string('file_path')->nullable();
            $table->timestamp('revoked_at')->nullable();
            $table->string('revocation_reason')->nullable();
            $table->timestamps();

            $table->unique('assignment_id', 'certificates_assignment_unique');
        });

        Schema::create('notifications', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignId('assignment_id')->nullable()
                ->constrained('user_training_assignments')->cascadeOnDelete();
            $table->string('type')->index();
            $table->date('scheduled_for');
            $table->timestamp('sent_at')->nullable();
            $table->json('payload')->nullable();
            $table->timestamps();

            // One notification per assignment + type + scheduled day, so re-running the
            // reminder job never double-sends.
            $table->unique(['assignment_id', 'type', 'scheduled_for'], 'notifications_idempotency_unique');
        });

        Schema::create('notification_deliveries', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->cascadeOnDelete();
            $table->foreignId('notification_id')->constrained()->cascadeOnDelete();
            $table->string('channel')->default('mail');
            $table->string('status')->default('queued')->index();
            $table->timestamp('attempted_at')->nullable();
            $table->text('failure_reason')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('notification_deliveries');
        Schema::dropIfExists('notifications');
        Schema::dropIfExists('certificates');
        Schema::dropIfExists('audit_logs');
        Schema::dropIfExists('compliance_events');
    }
};
